all:
  children:
    webservers:
      hosts:
        web-01:
          ansible_host: 18.207.136.173

        web-02:
          ansible_host: 44.222.102.251

        web-03:
          ansible_host: 44.200.81.138

        web-04:
          ansible_host: 44.222.232.192

        web-05:
          ansible_host: 100.28.231.1

      vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: /home/ylhan/.ssh/EC2-Tutorial.pem
